name: groundingdino
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - cudatoolkit=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pip
  - pip:
      - -r requirements.txt
